deployment

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -73,155 +73,155 @@ jobs:
           cd frontend
           npm run lint
 
-  analyze-code:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # analyze-code:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Install dependencies
-        run: |
-          cd frontend
-          npm install
-          cd ..
-          pip install -r ./rest_api/requirements.txt
+  #     - name: Install dependencies
+  #       run: |
+  #         cd frontend
+  #         npm install
+  #         cd ..
+  #         pip install -r ./rest_api/requirements.txt
 
-      - name: Analyze with SonarCloud
-        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
-        env:
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        with:
-          # Additional arguments for the SonarScanner CLI
-          args:
-              -Dsonar.organization=mingyuan13
-              -Dsonar.projectKey=MingyuAN13_TrainMate
-              -Dsonar.sources=. 
-              -Dsonar.login=$SONAR_TOKEN
-              -Dproject.settings=.ci/sonar-project.properties
-              -X
+  #     - name: Analyze with SonarCloud
+  #       uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
+  #       env:
+  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  #       with:
+  #         # Additional arguments for the SonarScanner CLI
+  #         args:
+  #             -Dsonar.organization=mingyuan13
+  #             -Dsonar.projectKey=MingyuAN13_TrainMate
+  #             -Dsonar.sources=. 
+  #             -Dsonar.login=$SONAR_TOKEN
+  #             -Dproject.settings=.ci/sonar-project.properties
+  #             -X
 
-      # - name: Analyze code with Understand
-      #   run: |
-      #     und -verbose analyze -db .ci/understand-settings.und || true
-      #     und -verbose metrics .ci/understand-settings.und || true
-      #     und export -format longnoroot -dependencies file csv .ci/dependencies.csv .ci/understand-settings.und
+  #     # - name: Analyze code with Understand
+  #     #   run: |
+  #     #     und -verbose analyze -db .ci/understand-settings.und || true
+  #     #     und -verbose metrics .ci/understand-settings.und || true
+  #     #     und export -format longnoroot -dependencies file csv .ci/dependencies.csv .ci/understand-settings.und
 
-      # - name: Upload Understand artifacts
-      #   uses: actions/upload-artifact@v2
-      #   with:
-      #     name: understand-artifacts
-      #     path: |
-      #       .ci/understand-settings.csv
-      #       .ci/dependencies.csv
-      - name: Fetch SonarCloud Issues
-        env:
-          SONAR_PROJECT_KEY: MingyuAN13_TrainMate
-        run: |
-          mkdir -p .ci
-          curl -s -u ${{ secrets.SONAR_TOKEN }}: \
-          "https://sonarcloud.io/api/measures/component_tree?component=${{ env.SONAR_PROJECT_KEY }}&metricKeys=complexity,ncloc,comment_lines_density,functions&ps=500" \
-            > .ci/sonar_analysis.json
-          if [ ! -s .ci/sonar_analysis.json ]; then
-          echo "Failed to generate sonar_analysis.json"
-          exit 1
-          fi
+  #     # - name: Upload Understand artifacts
+  #     #   uses: actions/upload-artifact@v2
+  #     #   with:
+  #     #     name: understand-artifacts
+  #     #     path: |
+  #     #       .ci/understand-settings.csv
+  #     #       .ci/dependencies.csv
+  #     - name: Fetch SonarCloud Issues
+  #       env:
+  #         SONAR_PROJECT_KEY: MingyuAN13_TrainMate
+  #       run: |
+  #         mkdir -p .ci
+  #         curl -s -u ${{ secrets.SONAR_TOKEN }}: \
+  #         "https://sonarcloud.io/api/measures/component_tree?component=${{ env.SONAR_PROJECT_KEY }}&metricKeys=complexity,ncloc,comment_lines_density,functions&ps=500" \
+  #           > .ci/sonar_analysis.json
+  #         if [ ! -s .ci/sonar_analysis.json ]; then
+  #         echo "Failed to generate sonar_analysis.json"
+  #         exit 1
+  #         fi
       
-      - name: Upload Sonar Analysis JSON
-        uses: actions/upload-artifact@v2
-        with:
-          name: sonar-analysis-json
-          path: .ci/sonar_analysis.json
+  #     - name: Upload Sonar Analysis JSON
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: sonar-analysis-json
+  #         path: .ci/sonar_analysis.json
 
-      - name: Download Sonar Analysis Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: sonar-analysis-json
-          path: .ci
+  #     - name: Download Sonar Analysis Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: sonar-analysis-json
+  #         path: .ci
 
-      - name: Convert Sonar JSON to CSV
-        working-directory: .ci
-        run: |
-          python3 generate_csv.py sonar_analysis.json sonar_analysis.csv
+  #     - name: Convert Sonar JSON to CSV
+  #       working-directory: .ci
+  #       run: |
+  #         python3 generate_csv.py sonar_analysis.json sonar_analysis.csv
 
-      - name: Upload CSV as Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: sonar-analysis-csv
-          path: .ci/sonar_analysis.csv
+  #     - name: Upload CSV as Artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: sonar-analysis-csv
+  #         path: .ci/sonar_analysis.csv
       
-      - name: Set up OWASP Dependency-Check
-        run: |
-          wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.3/dependency-check-10.0.3-release.zip
-          unzip dependency-check-10.0.3-release.zip -d dependency-check
-          ls dependency-check # List files to confirm correct extraction
+  #     - name: Set up OWASP Dependency-Check
+  #       run: |
+  #         wget https://github.com/jeremylong/DependencyCheck/releases/download/v10.0.3/dependency-check-10.0.3-release.zip
+  #         unzip dependency-check-10.0.3-release.zip -d dependency-check
+  #         ls dependency-check # List files to confirm correct extraction
 
-      - name: Run Dependency-Check
-        env:
-          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
-        run: dependency-check/dependency-check/bin/dependency-check.sh --project "TrainMate" --scan . --out dependency_graph --format CSV --nvdApiKey $NVD_API_KEY
+  #     - name: Run Dependency-Check
+  #       env:
+  #         NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
+  #       run: dependency-check/dependency-check/bin/dependency-check.sh --project "TrainMate" --scan . --out dependency_graph --format CSV --nvdApiKey $NVD_API_KEY
 
-      - name: Upload CSV as Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: dependency-csv-b
-          path:  /home/runner/work/TrainMate/TrainMate/dependency_graph/dependency-check-report.csv  
+  #     - name: Upload CSV as Artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: dependency-csv-b
+  #         path:  /home/runner/work/TrainMate/TrainMate/dependency_graph/dependency-check-report.csv  
 
-      - name: Parse Dependency-Check CSV
-        run: |
-          python3 .ci/convert_csv.py
+  #     - name: Parse Dependency-Check CSV
+  #       run: |
+  #         python3 .ci/convert_csv.py
 
-      - name: Upload CSV as Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: dependency-csv
-          path: .ci/parsed_dependency_report.csv
+  #     - name: Upload CSV as Artifact
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: dependency-csv
+  #         path: .ci/parsed_dependency_report.csv
 
-  analyze-duplication:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # analyze-duplication:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Set up Java
-        uses: actions/setup-java@v2
-        with:
-          java-version: 17
-          distribution: 'adopt'
+  #     - name: Set up Java
+  #       uses: actions/setup-java@v2
+  #       with:
+  #         java-version: 17
+  #         distribution: 'adopt'
 
-      - name: Run Simian for code duplication analysis
-        run: |
-          java -jar .ci/simian-4.0.0.jar -balanceParentheses -failOnDuplication -ignoreCharacterCase -ignoreCurlyBraces -ignoreIdentifierCase -ignoreModifiers -ignoreStringCase -threshold=6 -formatter="yaml" "./rest_api/*.py" "./frontend/src/*.ts" "./frontend/src/*.tsx"
+  #     - name: Run Simian for code duplication analysis
+  #       run: |
+  #         java -jar .ci/simian-4.0.0.jar -balanceParentheses -failOnDuplication -ignoreCharacterCase -ignoreCurlyBraces -ignoreIdentifierCase -ignoreModifiers -ignoreStringCase -threshold=6 -formatter="yaml" "./rest_api/*.py" "./frontend/src/*.ts" "./frontend/src/*.tsx"
 
-  validate-analysis:
-    runs-on: ubuntu-latest
-    needs: analyze-code
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  # validate-analysis:
+  #   runs-on: ubuntu-latest
+  #   needs: analyze-code
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      - name: Set up Rust
-        uses: actions-rust-lang/setup-rust-toolchain@v1
+  #     - name: Set up Rust
+  #       uses: actions-rust-lang/setup-rust-toolchain@v1
 
-      - name: Download Sonar Analysis CSV Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: sonar-analysis-csv
-          path: .ci
+  #     - name: Download Sonar Analysis CSV Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: sonar-analysis-csv
+  #         path: .ci
       
-      - name: Download Dependency Graph Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: dependency-csv
-          path: .ci
+  #     - name: Download Dependency Graph Artifact
+  #       uses: actions/download-artifact@v2
+  #       with:
+  #         name: dependency-csv
+  #         path: .ci
 
-      - name: List files in .ci directory after CSV generation
-        run: |
-          ls -al .ci
+  #     - name: List files in .ci directory after CSV generation
+  #       run: |
+  #         ls -al .ci
 
-      - name: Validate analysis
-        run: |
-          cd .ci/understand-validator
-          cargo run --release
+  #     - name: Validate analysis
+  #       run: |
+  #         cd .ci/understand-validator
+  #         cargo run --release
 
   build-frontend:
     runs-on: ubuntu-latest
@@ -392,9 +392,24 @@ jobs:
           kubectl apply -f deployment.yaml
           kubectl apply -f service.yaml
 
+      - name: Check logs for all containers
+        run: |
+          PODS=$(kubectl get pods -l app=trainmate -o jsonpath='{.items[*].metadata.name}')
+          for POD in $PODS; do
+            echo "Logs for pod: $POD"
+            kubectl logs $POD -c frontend
+            kubectl logs $POD -c rest-api
+            kubectl logs $POD -c rest-api-test
+            kubectl logs $POD -c cypress
+          done
+
+      - name: Wait for pods to be ready
+        run: |
+          kubectl wait --for=condition=ready pod -l app=trainmate --timeout=300s
+
       - name: Verify Deployment
         run: |
-          kubectl get pods
+          kubectl get pods --selector=app=trainmate --show-labels
           kubectl get pv
           kubectl get pvc
           
